CREATE DATABASE noteDB;

USE noteDB;

CREATE TABLE notes(
    ID INT UNIQUE PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(200) NOT NULL,
    content VARCHAR(500) NOT NULL,
    createdAt TIMESTAMP DEFAULT NOW()
)